name: CI
on:
  push:
    branches:
      - hexo
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v1
        with:
          ref: hexo
#      - name: Clean
#        uses: heowc/action-hexo@main
#        with:
#          args: clean
      - name: Generate
        uses: heowc/action-hexo@main
        with:
          args: generate
      - name: Deploy
        uses: heowc/action-hexo@main
        env:
          EMAIL: inkdp.qq.com
          NAME: InkDP
        with:
          args: deploy

